# Generated by Django 6.0.7 on 2026-08-12 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=50)),
                ('relationship', models.CharField(blank=True, choices=[('spouse', '配偶'), ('child', '子女'), ('sibling', '手足'), ('other', '其他')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
