# Generated by Django 6.0.7 on 2026-08-12 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=50)),
                ('activity_type', models.CharField(blank=True, choices=[('exercise', '運動'), ('lecture', '講座'), ('social', '社交活動'), ('checkup', '健康檢查')], max_length=30)),
                ('activity_location', models.CharField(blank=True, max_length=100)),
                ('activity_region', models.CharField(blank=True, choices=[('north', '北部'), ('central', '中部'), ('south', '南部'), ('east', '東部')], max_length=30)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activity_description', models.TextField(blank=True)),
                ('source_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('registered', '已報名'), ('completed', '已完成'), ('cancelled', '已取消')], max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to=settings.AUTH_USER_MODEL)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='activities.healthinformation')),
            ],
        ),
    ]
