# Generated by Django 6.0.7 on 2026-08-12 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('audio_path', models.CharField(blank=True, max_length=255)),
                ('transcription', models.TextField(blank=True)),
                ('diary_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_fluency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('logic_completeness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('emotion_description_completeness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('emotion_analysis_result', models.CharField(blank=True, max_length=50)),
                ('ai_feedback', models.TextField(blank=True)),
                ('analysis_time', models.DateTimeField(auto_now_add=True)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='diary.diary')),
            ],
        ),
    ]
