# Generated by Django 6.0.7 on 2026-08-12 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthDashboardRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attention_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('executive_function_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('language_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('working_memory_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('math_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('visual_spatial_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('brain_age', models.IntegerField(blank=True, null=True)),
                ('trend_alert_level', models.CharField(blank=True, choices=[('low', '低'), ('medium', '中'), ('high', '高')], max_length=10)),
                ('report_type', models.CharField(blank=True, choices=[('weekly', '週報'), ('monthly', '月報'), ('manual', '手動產生')], max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
