# Generated by Django 6.0.7 on 2026-08-12 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('category_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=50)),
                ('game_description', models.TextField(blank=True)),
                ('default_difficulty', models.CharField(blank=True, choices=[('easy', '簡單'), ('medium', '中等'), ('hard', '困難')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('game_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.gamecategory')),
            ],
        ),
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reaction_time', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', '簡單'), ('medium', '中等'), ('hard', '困難')], max_length=20)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('played_date', models.DateField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
