# Generated by Django 6.0.7 on 2026-09-12 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketShoppingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', '簡單'), ('medium', '中等'), ('hard', '困難')], max_length=20)),
                ('target_items', models.JSONField()),
                ('option_items', models.JSONField()),
                ('budget', models.IntegerField(default=200)),
                ('spent_amount', models.IntegerField()),
                ('correct_change', models.IntegerField()),
                ('item_attempt_count', models.IntegerField(default=0)),
                ('change_attempt_count', models.IntegerField(default=0)),
                ('item_first_try_correct', models.BooleanField(blank=True, null=True)),
                ('change_first_try_correct', models.BooleanField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_shopping_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
