# Generated by Django 6.0.7 on 2026-09-24 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='is_enabled',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='gamerecord',
            old_name='reaction_time',
            new_name='response_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_name',
        ),
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='default_difficulty',
            field=models.CharField(blank=True, choices=[('basic', '初階'), ('intermediate', '中階'), ('advanced', '進階')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gamecategory',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('basic', '初階'), ('intermediate', '中階'), ('advanced', '進階')], max_length=20),
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('in_progress', '進行中'), ('finished', '結束')], default='in_progress', max_length=20)),
                ('question_number', models.PositiveIntegerField(default=0)),
                ('current_question', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('state', models.JSONField(default=dict)),
                ('is_pretest', models.BooleanField(default=False)),
                ('avg_response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameStepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_logs', to='games.gamesession')),
            ],
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['game', 'user'], name='games_games_game_id_f46b33_idx'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.UniqueConstraint(fields=('game', 'client_session_id'), name='unique_client_session_per_game'),
        ),
    ]
