# Generated by Django 6.0.7 on 2026-09-22 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=50)),
                ('is_pretest', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketRouteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_stage', models.CharField(max_length=20)),
                ('total_questions', models.IntegerField(default=20)),
                ('answered_count', models.IntegerField()),
                ('correct_count', models.IntegerField()),
                ('timeout_count', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('avg_response_time_ms', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_route_session', to='games.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='MarketRouteStepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('attempt_number', models.IntegerField()),
                ('stage', models.CharField(max_length=20)),
                ('target_position', models.CharField(max_length=10)),
                ('answer_position', models.CharField(blank=True, max_length=10, null=True)),
                ('is_correct', models.BooleanField()),
                ('is_timeout', models.BooleanField()),
                ('distractor_count', models.IntegerField()),
                ('exposure_time_ms', models.IntegerField()),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('paused_duration_ms', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_route_steps', to='games.gamesession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'question_number'], name='games_marke_session_83a3bf_idx')],
            },
        ),
    ]
