# Generated by Django 6.0.7 on 2026-09-14 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSortResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('raw_metrics', models.JSONField(blank=True, null=True)),
                ('z_scores', models.JSONField(blank=True, null=True)),
                ('cognitive_flexibility_score', models.IntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_sort_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
