# Generated by Django 6.0.7 on 2026-09-29 02:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('in_progress', '進行中'), ('finished', '已完成')], default='in_progress', max_length=20)),
                ('question_number', models.PositiveIntegerField(default=0)),
                ('current_question', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('state', models.JSONField(default=dict)),
                ('is_pretest', models.BooleanField(default=False)),
                ('avg_response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='games.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameStepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_logs', to='games.gamesession')),
            ],
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['game', 'user'], name='games_games_game_id_f46b33_idx'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.UniqueConstraint(fields=('game', 'client_session_id'), name='unique_client_session_per_game'),
        ),
    ]
