# Generated by Django 6.0.7 on 2026-09-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_marketshoppingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketshoppingsession',
            name='consecutive_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketshoppingsession',
            name='current_question',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='marketshoppingsession',
            name='current_question_had_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketshoppingsession',
            name='current_wrong_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketshoppingsession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketshoppingsession',
            name='total_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketshoppingsession',
            name='total_questions',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='marketshoppingsession',
            name='difficulty',
            field=models.CharField(choices=[('easy', '簡單'), ('medium', '中等'), ('hard', '困難')], default='easy', max_length=20),
        ),
    ]
