# Generated by Django 6.0.7 on 2026-09-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_marketshoppingsession_consecutive_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketshoppingsession',
            name='first_try_correct_count',
            field=models.IntegerField(default=0),
        ),
    ]
