# Generated by Django 6.0.7 on 2026-09-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_marketsortresult'),
        ('games', '0005_seed_market_shopping_game'),
    ]

    operations = [
    ]
